# Generated by Django 2.1.7 on 2019-03-29 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('sent', 'Отправлена'), ('received', 'Получена'), ('accepted', 'Одобрено'), ('refused', 'Отказано'), ('completed', 'Выдано')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('phone', models.CharField(max_length=16)),
                ('passport', models.CharField(max_length=11)),
                ('score', models.IntegerField()),
                ('referral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('rotation_start_at', models.DateTimeField()),
                ('rotation_stop_at', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('credit_mortgage', 'Ипотека'), ('credit_consumer', 'Потребительский кредит'), ('credit_car', 'Автокредит')], max_length=32)),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Agent')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client'),
        ),
        migrations.AddField(
            model_name='application',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product'),
        ),
    ]
